# title: "Sam Foreman"
date: last-modified
lightbox: true
# date: today
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
# appendix-cite-as: display
favicon: "favicon.svg"
# twitter-card: true
site-url: "https://cs.utexas.edu/~mmuaz"
google-scholar: true
citeproc: true
# filters:
#   - lightbox
# lightbox: auto
project:
  type: website
  output-dir: "docs"
  preview:
    port: 9090
  render:
    # - '**/**/*.qmd'
    - "index.qmd"
    - "./qmd/papers/token-*/*.qmd"
    - "!posts/dope-*/*.qmd"
    - "posts/**/*.qmd"
    # - qmd/drop-*/*.qmd
    # - qmd/megatron*/*.qmd
    # - qmd/blog/*.qmd
author:
  name: "Muhammad Muaz"
  url: https://cs.utexas.edu/~mmuaz
  email: m.muaz@utexas.edu
  # affiliation: Argonne National Laboratory
  # affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
citation:
   author: Muhammad Muaz
   type: webpage
   title: "Personal Website"
   url: https://cs.utexas.edu/~mmuaz
execute:
  # keep-ipynb: true
  # keep-md: true
  freeze: auto
# header-includes: |
#     <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
#     <script src="https://twemoji.maxcdn.com/v/latest/twemoji.min.js" crossorigin="anonymous"></script>
#     <script>
#         $(document).ready
#         (
#           function()
#           {
#                 twemoji.parse(document.body);
#           }
#         );
#     </script>

metadata-files:
  - quarto/_website.yml
  - quarto/_format.yml
  # - _reveal.yml
